project_name: sail
builds:
  - env: [CGO_ENABLED=0]
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - format: tar.gz
    format_overrides:
      - goos: windows
        format: zip

dockers:
  - image_templates:
      - sailpoint/sailpoint-cli:{{.Tag}}
    use: buildx
    dockerfile: Dockerfile
    build_flag_templates:
      - "--platform=linux/amd64"

brews:
  - name: sailpoint-cli
    homepage: "https://github.com/sailpoint-oss/sailpoint-cli"
    tap:
      owner: sailpoint-oss
      name: homebrew-tap
    commit_author:
      name: colin-mckibben-sp
      email: colin.mckibben@sailpoint.com
