name: PRB
env:
  SAIL_CLIENT_ID: ${{secrets.CLI_TEST_TENANT_CLIENT_ID}}
  SAIL_CLIENT_SECRET: ${{secrets.CLI_TEST_TENANT_CLIENT_SECRET}}
  SAIL_BASE_URL: https://css-255.api.identitynow.com

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  sailpoint-cli-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Test
        run: go test -v -count=1 ./...

      - name: Install
        run: go build -o sail.exe

      - name: Init connector project
        run: ./sail.exe conn init connTest

      - name: Build and package connector zip file
        working-directory: ./connTest
        run: |
          npm install
          npm run pack-zip
