name: PRB

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  sp-cli-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Test
        run: go test -v -count=1 ./...

      - name: Install
        run: make install
